# Generated by Django 5.1.6 on 2025-04-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SongFeedback',
            new_name='SongDB',
        ),
    ]
