# Generated by Django 5.1.6 on 2025-04-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0002_rename_songfeedback_songdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='songdb',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='songdb',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
